/*SELECT * FROM PRODUTO_ESPECIFICACAO_TECNICA PET
SELECT * FROM PRODUTO_GRADE_ECOMMERCE*/

SELECT
	PRODUTOS.IDSUBPRODUTO,
	PRODUTOS.IDCODBARPROD,
	CASE
		WHEN LENGTH (DESCRICAO) > 0 THEN  DESCRICAO
		ELSE OBSESPECIFIC
	END DESCRICAO
FROM
	(SELECT
		PRODUTO_GRADE_ECOMMERCE.IDSUBPRODUTO,
		PRODUTO_GRADE.IDCODBARPROD
	FROM
		PRODUTO_GRADE_ECOMMERCE,
		PRODUTO_GRADE
	WHERE
		PRODUTO_GRADE_ECOMMERCE.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
		PRODUTO_GRADE_ECOMMERCE.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO AND
		IDCONFIGECOMMERCE = 1 AND
		DESCRICAO = 'T') PRODUTOS
LEFT JOIN		
	(SELECT
		PRODUTO_GRADE_ECOMMERCE.IDSUBPRODUTO,
		PRODUTO_GRADE_ECOMMERCE.DESCRICAO
	FROM
		PRODUTO_GRADE_ECOMMERCE
	WHERE
		IDCONFIGECOMMERCE = 3 AND
		DESCRICAO IS NOT NULL) DESCRECOMMERCE ON PRODUTOS.IDSUBPRODUTO = DESCRECOMMERCE.IDSUBPRODUTO
 LEFT JOIN
	(SELECT
		IDCODBARPROD,
		OBSESPECIFIC
	FROM
		PRODUTO_ESPECIFICACAO_TECNICA) DESCRTEC ON PRODUTOS.IDCODBARPROD = DESCRTEC.IDCODBARPROD