SELECT UNIQUE
	NFS.IDSUBPRODUTO,
	DESCRRESPRODUTO,
	FABRICANTE,
	EST_LOJA1,
	EST_LOJA2,
	EST_LOJA3,
	EST_MLFULL 
FROM	
	(SELECT
		N.NUMNOTA,
		CF.IDCLIFOR,
		CF.NOME,
		EA.IDSUBPRODUTO,
		N.IDUSUARIO,
		U.NOMEUSUARIO 
	FROM 
		NOTAS N,
		NOTAS_ENTRADA_SAIDA NES,
		ESTOQUE_ANALITICO EA,
		CLIENTE_FORNECEDOR CF,
		USUARIO U
	WHERE
		N.IDPLANILHA = NES.IDPLANILHA AND
		NES.IDPLANILHA = EA.IDPLANILHA AND
		EA.IDPLANILHA = N.IDPLANILHA AND
		N.IDCLIFOR = CF.IDCLIFOR AND
		N.IDUSUARIO = U.IDUSUARIO AND
		NES.IDOPERACAO = 3001 AND
		EA.IDLOCALRETIRADA IN (28, 45, 50, 47, 50, 53, 56, 58) AND
		U.IDEMPRESA = :RA_EMPRESAUSER AND
		DATE(N.DTMOVIMENTO) BETWEEN :RA_DTINI AND :RA_DT_FIM)NFS LEFT JOIN
	-----INF SOBRE OS PRODS(CODIGO, DESCRICAO, MARCA E ESTOQUES)\/\/\/\/\/\/
	(SELECT
		INF_PROD.IDSUBPRODUTO,
		DESCRRESPRODUTO,
		FABRICANTE,
		EST_LOJA1,
		EST_LOJA2,
		EST_LOJA3,
		EST_MLFULL
	FROM
	(SELECT UNIQUE 
		PG.IDSUBPRODUTO,
		PG.DESCRRESPRODUTO,
		P.FABRICANTE
	FROM
		PRODUTOS_SALDOS_VIEW psv,
		PRODUTO_GRADE pg,
		PRODUTO p
	WHERE
		PSV.IDSUBPRODUTO = PG.IDSUBPRODUTO AND
		PSV.IDSUBPRODUTO = PG.IDSUBPRODUTO AND
		P.IDPRODUTO = PG.IDPRODUTO) INF_PROD LEFT JOIN
	(SELECT
		LOJA1.IDSUBPRODUTO,
		COALESCE(EST_LOJA1,0) EST_LOJA1,
		COALESCE(EST_LOJA2,0) EST_LOJA2,
		COALESCE(EST_LOJA3,0) EST_LOJA3,
		COALESCE(EST_MLFULL,0) EST_MLFULL
	FROM
		(SELECT
			PSV.IDSUBPRODUTO,
			COALESCE(PSV.QTDATUALESTOQUE,0) EST_LOJA1
		FROM
			ESTOQUE_SALDO_ATUAL PSV
		WHERE
			PSV.IDLOCALESTOQUE = 1 AND
			PSV.IDEMPRESA = 1) LOJA1 LEFT JOIN 
		(SELECT
			PSV.IDSUBPRODUTO,
			COALESCE(PSV.QTDATUALESTOQUE,0) EST_LOJA2
		FROM
			ESTOQUE_SALDO_ATUAL PSV
		WHERE
			PSV.IDLOCALESTOQUE = 21 AND
			PSV.IDEMPRESA = 2) LOJA2 ON LOJA1.IDSUBPRODUTO = LOJA2.IDSUBPRODUTO LEFT JOIN
		(SELECT
			PSV.IDSUBPRODUTO,
			COALESCE(PSV.QTDATUALESTOQUE,0) EST_LOJA3
		FROM
			ESTOQUE_SALDO_ATUAL PSV
		WHERE
			PSV.IDLOCALESTOQUE = 31 AND
			PSV.IDEMPRESA = 3) LOJA3 ON LOJA1.IDSUBPRODUTO = LOJA3.IDSUBPRODUTO LEFT JOIN
		(SELECT
			PSV.IDSUBPRODUTO,
			COALESCE(PSV.QTDATUALESTOQUE,0) EST_MLFULL
		FROM
			ESTOQUE_SALDO_ATUAL PSV
		WHERE
			PSV.IDLOCALESTOQUE = 19 AND
			PSV.IDEMPRESA = 1) MLFULL ON LOJA1.IDSUBPRODUTO = MLFULL.IDSUBPRODUTO ) ESTOQUES ON 
			INF_PROD.IDSUBPRODUTO = ESTOQUES.IDSUBPRODUTO) MAIN ON NFS.IDSUBPRODUTO  = MAIN.IDSUBPRODUTO 
	
ORDER BY FABRICANTE 
	
	