--SELECT * FROM PRODUTO_GRADE_ECOMMERCE WHERE IDSUBPRODUTO = 10864 AND IDCONFIGECOMMERCE = 2
SELECT
	PRODUTOS.IDSUBPRODUTO,
	PRODUTO_GRADE.DESCRRESPRODUTO,
	PRODUTO.FABRICANTE,
	ULTIMA_VENDA,
	ESTOQUE,
	PRODUTOS.VALPRECOVAREJO 
FROM
	PRODUTO_GRADE,
	PRODUTO,
	--PRODUTOS ANUNCIADOS NO IDERIS \/	
	(SELECT
		PROD_IDERIS1.IDSUBPRODUTO,
		ULTIMA_VENDA,
		ESTOQUE.ESTOQUE,
		VALPRECOVAREJO
	FROM
		(SELECT 
			IDSUBPRODUTO
		FROM 
			PRODUTO_GRADE_ECOMMERCE 
		WHERE 
			IDCONFIGECOMMERCE = 3 AND 
			DESCRICAO IS NOT NULL
			/*PRODUTO_GRADE_ECOMMERCE.IDSUBPRODUTO IN (
				SELECT IDSUBPRODUTO FROM PRODUTO_GRADE WHERE QTDMINPONTAEST > 0)*/) PROD_IDERIS1 
		INNER JOIN
		(SELECT 
			IDSUBPRODUTO
		FROM 
			PRODUTO_GRADE_ECOMMERCE 
		WHERE 
			IDCONFIGECOMMERCE = 2 AND 
			DESCRICAO IS NOT NULL
			/*PRODUTO_GRADE_ECOMMERCE.IDSUBPRODUTO IN (
				SELECT IDSUBPRODUTO FROM PRODUTO_GRADE WHERE QTDMINPONTAEST > 0)*/) PROD_IDERIS2
				ON PROD_IDERIS1.IDSUBPRODUTO = PROD_IDERIS2.IDSUBPRODUTO 
		INNER JOIN 
		--produtos sem movimento no periodo
		(SELECT 
			IDSUBPRODUTO,
			MAX(DTMOVIMENTO) ULTIMA_VENDA
		FROM 
			ESTOQUE_ANALITICO ea 
		WHERE 
			TIPOCATEGORIA = 'A' AND
			DTMOVIMENTO < :RA_DT 
		GROUP BY
			IDSUBPRODUTO) SEM_MOVIMENTO ON PROD_IDERIS2.IDSUBPRODUTO = SEM_MOVIMENTO.IDSUBPRODUTO
		INNER JOIN
		(SELECT 
			IDSUBPRODUTO, SUM(QTDDISPONIVEL) ESTOQUE
		FROM 
			PRODUTOS_SALDOS_VIEW psv
		WHERE 
			IDLOCALESTOQUE IN (:RA_LOCAL)
		GROUP BY 
			IDSUBPRODUTO )ESTOQUE ON SEM_MOVIMENTO.IDSUBPRODUTO = ESTOQUE.IDSUBPRODUTO
		INNER JOIN
		(SELECT 
			IDSUBPRODUTO, 
			VALPRECOVAREJO 
		FROM 
			POLITICA_PRECO_PRODUTO
		GROUP BY 
			IDSUBPRODUTO, 
			VALPRECOVAREJO) PRECO ON  ESTOQUE.IDSUBPRODUTO = PRECO.IDSUBPRODUTO) PRODUTOS 
WHERE
	PRODUTO.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
	PRODUTOS.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO AND
	PRODUTO_GRADE.IDSUBPRODUTO = PRODUTOS.IDSUBPRODUTO AND
	UPPER(PRODUTO.MARCA) LIKE '%'|| :RA_MARCA ||'%' AND
	PRODUTO_GRADE.FLAGINATIVO = 'F' AND
	ESTOQUE > 0
		
		
		