SELECT
	PRODUTO.IDPRODUTO,
	PRODUTO.IDSUBPRODUTO,
	PRODUTO.DESCRRESPRODUTO,
	PRODUTO.FABRICANTE,
	COALESCE(VENDAS_NO_PERIODO1,0) VENDAS_NO_PERIODO1,
	COALESCE(ESTOQUE_DISPONIVEL1,0) ESTOQUE_DISPONIVEL1,
	COALESCE(MÉDIA_VENDAS_DIARIA1,0) MÉDIA_VENDAS_DIARIA1,
	CASE 
		WHEN VENDAS_NO_PERIODO1 > 0 THEN COALESCE(CAST(PREVISAO1 AS VARCHAR),'0')
		ELSE 'ND'
	END PREVISAO1,
	COALESCE(VENDAS_NO_PERIODO2,0) VENDAS_NO_PERIODO2,
	COALESCE(DADOS2.ESTOQUE_DISPONIVEL2,0) ESTOQUE_DISPONIVEL2,
	COALESCE(MÉDIA_VENDAS_DIARIA2,0) MÉDIA_VENDAS_DIARIA2,
	CASE 
		WHEN VENDAS_NO_PERIODO2 > 0 THEN COALESCE(CAST(PREVISAO2 AS VARCHAR),'0')
		ELSE 'ND'
	END PREVISAO2,
	COALESCE(VENDAS_NO_PERIODO3,0) VENDAS_NO_PERIODO3,
	COALESCE(ESTOQUE_DISPONIVEL3,0) ESTOQUE_DISPONIVEL3,
	COALESCE(MÉDIA_VENDAS_DIARIA3,0) MÉDIA_VENDAS_DIARIA3,
	CASE 
		WHEN VENDAS_NO_PERIODO3 > 0 THEN COALESCE(CAST(PREVISAO3 AS VARCHAR),'0')
		ELSE 'ND'
	END PREVISAO3,
	COALESCE(ESTOQUE_DISPONIVEL,0) ESTOQUE_DISPONIVEL_VENDA,
	CASE
		WHEN VENDAS_TOTAL_PERIODO > 0 THEN COALESCE(CAST(PREVISAO_TOTAL AS VARCHAR),'0')
		ELSE 'ND'
	END PREVISAO_TOTAL
FROM
	(SELECT
		P.IDPRODUTO,
		PG.IDSUBPRODUTO,
		PG.DESCRRESPRODUTO,
		P.FABRICANTE
	FROM
		PRODUTO P,
		PRODUTO_GRADE PG LEFT JOIN PRODUTO_FORNECEDOR PF ON 
			PG.IDPRODUTO = PF.IDPRODUTO AND PG.IDSUBPRODUTO = PF.IDSUBPRODUTO 
	WHERE
		P.IDPRODUTO = PG.IDPRODUTO AND
		PF.IDCLIFOR = :RA_FORNECEDOR AND
		P.FABRICANTE LIKE UPPER('%'||:RA_FABRICANTE||'%'))PRODUTO LEFT JOIN		
	
	(SELECT
		ESTOQUE1.IDPRODUTO,
		ESTOQUE1.IDSUBPRODUTO,
		VENDAS1.VENDAS_NO_PERIODO1,
		ESTOQUE1.ESTOQUE_DISPONIVEL1,
		(VENDAS1.VENDAS_NO_PERIODO1/ :RA_DIAS_MEDIA) MÉDIA_VENDAS_DIARIA1,
		(ESTOQUE1.ESTOQUE_DISPONIVEL1/(VENDAS1.VENDAS_NO_PERIODO1/ :RA_DIAS_MEDIA)) PREVISAO1
	FROM
		(SELECT
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO,
			SUM(QTDPRODUTO)	VENDAS_NO_PERIODO1
		FROM
			ESTOQUE_ANALITICO EA
		WHERE
			EA.IDOPERACAO IN (3001, 1001, 1300, 1150) AND
			EA.TIPOCATEGORIA = 'A' AND
			EA.IDEMPRESABAIXAEST = 1 AND
			DTMOVIMENTO BETWEEN (TODAY - :RA_DIAS_MEDIA) AND TODAY
		GROUP BY
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO) VENDAS1 RIGHT JOIN
		(SELECT 
			IDPRODUTO,
			IDSUBPRODUTO,
			SUM(QTDDISPONIVEL) ESTOQUE_DISPONIVEL1
		FROM 
			PRODUTOS_SALDOS_VIEW
		WHERE
			IDLOCALESTOQUE = 1
		GROUP BY
			IDPRODUTO,
			IDSUBPRODUTO) ESTOQUE1 ON VENDAS1.IDPRODUTO = ESTOQUE1.IDPRODUTO AND 
			VENDAS1.IDSUBPRODUTO = ESTOQUE1.IDSUBPRODUTO) DADOS1 ON PRODUTO.IDPRODUTO = DADOS1.IDPRODUTO AND 
			PRODUTO.IDSUBPRODUTO = DADOS1.IDSUBPRODUTO 
			LEFT JOIN
	(SELECT
		ESTOQUE2.IDPRODUTO,
		ESTOQUE2.IDSUBPRODUTO,
		VENDAS2.VENDAS_NO_PERIODO2,
		ESTOQUE2.ESTOQUE_DISPONIVEL2,
		(VENDAS2.VENDAS_NO_PERIODO2/ :RA_DIAS_MEDIA) MÉDIA_VENDAS_DIARIA2,
		(ESTOQUE2.ESTOQUE_DISPONIVEL2/(VENDAS2.VENDAS_NO_PERIODO2/ :RA_DIAS_MEDIA)) PREVISAO2
	FROM
		(SELECT
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO,
			SUM(QTDPRODUTO)	VENDAS_NO_PERIODO2
		FROM
			ESTOQUE_ANALITICO EA 
		WHERE
			EA.IDOPERACAO IN (3001, 1001, 1300, 1152 ) AND
			EA.TIPOCATEGORIA = 'A' AND
			EA.IDEMPRESABAIXAEST = 2 AND
			DTMOVIMENTO BETWEEN (TODAY - :RA_DIAS_MEDIA) AND TODAY
		GROUP BY
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO
		UNION ALL
		SELECT
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO,
			SUM(QTDPRODUTO)	VENDAS_NO_PERIODO2
		FROM
			ESTOQUE_ANALITICO EA 
		WHERE
			EA.IDOPERACAO IN (1097) AND
			EA.TIPOCATEGORIA = 'A' AND
			EA.IDEMPRESABAIXAEST = 1 AND
			DTMOVIMENTO BETWEEN (TODAY - :RA_DIAS_MEDIA) AND TODAY
		GROUP BY
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO
		) VENDAS2 RIGHT JOIN
		(SELECT 
			IDPRODUTO,
			IDSUBPRODUTO,
			SUM(QTDDISPONIVEL) ESTOQUE_DISPONIVEL2
		FROM 
			PRODUTOS_SALDOS_VIEW
		WHERE
			IDLOCALESTOQUE = 21
		GROUP BY
			IDPRODUTO,
			IDSUBPRODUTO) ESTOQUE2 ON VENDAS2.IDPRODUTO = ESTOQUE2.IDPRODUTO AND 
			VENDAS2.IDSUBPRODUTO = ESTOQUE2.IDSUBPRODUTO) DADOS2 ON PRODUTO.IDPRODUTO = DADOS2.IDPRODUTO AND 
			PRODUTO.IDSUBPRODUTO = DADOS2.IDSUBPRODUTO 
			LEFT JOIN
	(SELECT
		ESTOQUE3.IDPRODUTO,
		ESTOQUE3.IDSUBPRODUTO,
		VENDAS3.VENDAS_NO_PERIODO3,
		ESTOQUE3.ESTOQUE_DISPONIVEL3,
		(VENDAS3.VENDAS_NO_PERIODO3/ :RA_DIAS_MEDIA) MÉDIA_VENDAS_DIARIA3,
		(ESTOQUE3.ESTOQUE_DISPONIVEL3/(VENDAS3.VENDAS_NO_PERIODO3/ :RA_DIAS_MEDIA)) PREVISAO3
	FROM
		(SELECT
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO,
			SUM(QTDPRODUTO)	VENDAS_NO_PERIODO3
		FROM
			ESTOQUE_ANALITICO EA
		WHERE
			EA.IDOPERACAO IN (3001, 1001, 1300, 1152) AND
			EA.TIPOCATEGORIA = 'A' AND
			EA.IDEMPRESABAIXAEST = 3 AND
			DTMOVIMENTO BETWEEN (TODAY - :RA_DIAS_MEDIA) AND TODAY
		GROUP BY
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO) VENDAS3 RIGHT JOIN
		(SELECT 
			IDPRODUTO,
			IDSUBPRODUTO,
			SUM(QTDDISPONIVEL) ESTOQUE_DISPONIVEL3
		FROM 
			PRODUTOS_SALDOS_VIEW
		WHERE
			IDLOCALESTOQUE = 31
		GROUP BY
			IDPRODUTO,
			IDSUBPRODUTO) ESTOQUE3 ON VENDAS3.IDPRODUTO = ESTOQUE3.IDPRODUTO AND 
			VENDAS3.IDSUBPRODUTO = ESTOQUE3.IDSUBPRODUTO) DADOS3 ON PRODUTO.IDPRODUTO = DADOS3.IDPRODUTO AND 
			PRODUTO.IDSUBPRODUTO = DADOS3.IDSUBPRODUTO
			LEFT JOIN
			
	(SELECT
		ESTOQUE_TOTAL.IDPRODUTO,
		ESTOQUE_TOTAL.IDSUBPRODUTO,
		VENDAS_TOTAL.VENDAS_TOTAL_PERIODO,
		ESTOQUE_TOTAL.ESTOQUE_DISPONIVEL,
		(VENDAS_TOTAL.VENDAS_TOTAL_PERIODO/ :RA_DIAS_MEDIA) MÉDIA_VENDAS_TOTAL,
		(ESTOQUE_TOTAL.ESTOQUE_DISPONIVEL/(VENDAS_TOTAL.VENDAS_TOTAL_PERIODO/ :RA_DIAS_MEDIA)) PREVISAO_TOTAL
	FROM
	
		(SELECT
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO,
			SUM(QTDPRODUTO)	VENDAS_TOTAL_PERIODO
		FROM
			ESTOQUE_ANALITICO EA
		WHERE
			EA.IDOPERACAO IN (3001, 1097, 1001, 1300, 1152) AND
			EA.TIPOCATEGORIA = 'A' AND
			EA.IDEMPRESABAIXAEST IN (1, 2, 3) AND
			DTMOVIMENTO BETWEEN (TODAY - :RA_DIAS_MEDIA) AND TODAY
		GROUP BY
			EA.IDSUBPRODUTO,
			EA.IDPRODUTO) VENDAS_TOTAL RIGHT JOIN
		(SELECT 
			IDPRODUTO,
			IDSUBPRODUTO,
			SUM(QTDDISPONIVEL) ESTOQUE_DISPONIVEL
		FROM 
			PRODUTOS_SALDOS_VIEW
		WHERE
			IDLOCALESTOQUE IN (1, 21, 31)
		GROUP BY
			IDPRODUTO,
			IDSUBPRODUTO) ESTOQUE_TOTAL ON VENDAS_TOTAL.IDPRODUTO = ESTOQUE_TOTAL.IDPRODUTO AND 
			VENDAS_TOTAL.IDSUBPRODUTO = ESTOQUE_TOTAL.IDSUBPRODUTO) TOTAL ON PRODUTO.IDPRODUTO = TOTAL.IDPRODUTO AND 
			PRODUTO.IDSUBPRODUTO = TOTAL.IDSUBPRODUTO
--WHERE
	--(VENDAS_NO_PERIODO1 > 0 OR VENDAS_NO_PERIODO2 > 0 OR VENDAS_NO_PERIODO3 > 0)

 
