--SELECT * FROM ESTOQUE_SALDO_ATUAL 

SELECT 
	PGE.IDSUBPRODUTO,
	PG.DESCRRESPRODUTO,
	PPP.VALPRECOVAREJO
	
FROM 
	PRODUTO_GRADE_ECOMMERCE PGE,
	PRODUTO_GRADE PG,
	POLITICA_PRECO_PRODUTO PPP,
	ESTOQUE_SALDO_ATUAL ESA
WHERE
	PGE.IDPRODUTO = ESA.IDPRODUTO AND 
	PGE.IDSUBPRODUTO = ESA.IDSUBPRODUTO AND
	PGE.IDPRODUTO = PG.IDPRODUTO  AND
	PGE.IDSUBPRODUTO = PG.IDSUBPRODUTO AND
	ESA.IDPRODUTO = PG.IDPRODUTO AND
	PGE.IDSUBPRODUTO = ESA.IDSUBPRODUTO AND
	PPP.IDSUBPRODUTO = ESA.IDSUBPRODUTO AND
	PPP.IDSUBPRODUTO = PG.IDSUBPRODUTO AND 
	PPP.IDSUBPRODUTO = PGE.IDSUBPRODUTO AND
	PPP.IDEMPRESA = 1 AND
	PPP.VALPRECOVAREJO > 0 AND
	IDCONFIGECOMMERCE = 2 AND 
	DESCRICAO IS NOT NULL AND
	PGE.IDSUBPRODUTO NOT IN(
					SELECT IDSUBPRODUTO FROM ESTOQUE_SALDO_ATUAL 
					WHERE IDLOCALESTOQUE IN (19,26) AND QTDATUALESTOQUE > 0 
					GROUP BY IDSUBPRODUTO ) AND
	PGE.IDSUBPRODUTO IN(
					SELECT IDSUBPRODUTO FROM ESTOQUE_ANALITICO 
					WHERE IDOPERACAO = 1097 GROUP BY IDSUBPRODUTO )
GROUP BY
	PGE.IDSUBPRODUTO,
	PG.DESCRRESPRODUTO,
	PPP.VALPRECOVAREJO
	