SELECT   
	TMP.MARCA,
	TMP.IDSUBPRODUTO,
	TMP.DESCRICAOPRODUTO,
	TMP.PRECO_VAREJO,
	SUM(TMP.QTDATUALESTOQUE) AS QTDATUALESTOQUE,
	TMP.MARCA,
	TMP.PONTA_DE_ESTOQUE 
FROM     
	(SELECT  
		UPPER((CASE LENGTH(COALESCE(LTRIM(RTRIM(PRODUTOS_VIEW.FABRICANTE)), 'SEM MARCA CADASTRADA'))
 		WHEN 0 THEN
			'SEM MARCA CADASTRADA'
 		ELSE
			COALESCE(UPPER(LTRIM(RTRIM(PRODUTOS_VIEW.FABRICANTE))), 'SEM MARCA CADASTRADA')
 		END)) AS MARCA,
		PRODUTOS_VIEW.IDSUBPRODUTO,
		PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
		POLITICA_PRECO_PRODUTO.VALPRECOVAREJO AS PRECO_VAREJO,
		COALESCE(PRODUTO_GRADE_SALDO_EST_VW.QTDATUALESTOQUE, 0) AS QTDATUALESTOQUE,
	(CASE
	WHEN PRODUTO_GRADE.QTDMINPONTAEST > 0 THEN
		'SIM'
	ELSE
		'NÃO' 
	END) PONTA_DE_ESTOQUE

	FROM    
		PRODUTO_GRADE_SALDO_EST_VW RIGHT OUTER JOIN PRODUTOS_VIEW ON
		(PRODUTO_GRADE_SALDO_EST_VW.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND
		PRODUTO_GRADE_SALDO_EST_VW.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO AND
		PRODUTO_GRADE_SALDO_EST_VW.IDEMPRESA IN (:RA_IDEMPRESA)),
		POLITICA_PRECO_PRODUTO,
		PRODUTO_GRADE
 	WHERE    
 		UPPER(PRODUTOS_VIEW.FLAGINATIVO) = 'F' AND
  		UPPER(PRODUTO_GRADE.FLAGBLOQUEIAVENDA) = 'F' AND
  		POLITICA_PRECO_PRODUTO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND
		((PRODUTOS_VIEW.FLAGINATIVO = :RA_STATUS) OR
 		(:RA_STATUS = '%')) AND
        POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO AND
		PRODUTOS_VIEW.IDSUBPRODUTO  = PRODUTO_GRADE.IDSUBPRODUTO AND
	  	POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO AND
        POLITICA_PRECO_PRODUTO.IDEMPRESA IN (:RA_IDEMPRESA) AND
	  	(PRODUTOS_VIEW.IDSUBPRODUTO NOT IN
			(SELECT IDSUBPRODUTO
 			FROM PRODUTO_GRADE_ECOMMERCE 
 			WHERE IDCONFIGECOMMERCE = 2 AND DESCRICAO IS NOT NULL) OR
		PRODUTOS_VIEW.IDSUBPRODUTO NOT IN
			(SELECT IDSUBPRODUTO
 			FROM PRODUTO_GRADE_ECOMMERCE 
 			WHERE IDCONFIGECOMMERCE = 3 AND DESCRICAO IS NOT NULL) OR
 		PRODUTOS_VIEW.IDSUBPRODUTO NOT IN
 			(SELECT IDSUBPRODUTO
 			FROM PRODUTO_GRADE_IMAGENS WHERE PATHIMAGEM IS NOT NULL))
 	) AS TMP

WHERE    
	((TMP.PRECO_VAREJO = 0 AND UPPER(:RA_PRECOZERADO) = 'Z') OR
	(UPPER(:RA_PRECOZERADO) = 'N' AND
	TMP.PRECO_VAREJO > 0) OR
	(UPPER(:RA_PRECOZERADO) = '%')) AND
	UPPER(TMP.MARCA) LIKE '%'|| :RA_MARCA ||'%' 
GROUP BY 
	TMP.MARCA,
	TMP.IDSUBPRODUTO,
	TMP.DESCRICAOPRODUTO,
	TMP.PRECO_VAREJO,TMP.MARCA,
	TMP.PONTA_DE_ESTOQUE 
ORDER BY 
	TMP.PRECO_VAREJO



