--SELECT FABRICANTE FROM PRODUTO
--SELECT * FROM POLITICA_PRECO_PRODUTO ppp 
/*SELECT 
	IDSUBPRODUTO, 
	SUM(QTDDISPONIVEL) SALDO_VENDAS 
FROM 
	PRODUTOS_SALDOS_VIEW 
WHERE 
	IDLOCALESTOQUE IN (1, 21, 31)
GROUP BY 
	IDSUBPRODUTO*/


SELECT 
	PGE.IDSUBPRODUTO,
	PG.DESCRRESPRODUTO,
	PPP.VALPRECOVAREJO,
	P.FABRICANTE,
	SALDO.SALDO_VENDAS,
	CASE 
		WHEN PG.QTDMINPONTAEST > 0 THEN 'SIM'
		ELSE 'NÃO'
	END PONTA_DE_ESTOQUE,
	CASE
		WHEN PG.FLAGINATIVO = 'T' THEN 'INATIVO'
		ELSE 'ATIVO'
	END ATIVO_INATIVO
FROM 
	PRODUTO_GRADE PG,
	PRODUTO P,
	PRODUTO_GRADE_ECOMMERCE PGE LEFT JOIN POLITICA_PRECO_PRODUTO PPP 
	ON PGE.IDSUBPRODUTO = PPP.IDSUBPRODUTO 
	LEFT JOIN (SELECT IDSUBPRODUTO, SUM(QTDDISPONIVEL) SALDO_VENDAS 
				FROM PRODUTOS_SALDOS_VIEW WHERE IDLOCALESTOQUE IN (1, 21, 31)
				GROUP BY IDSUBPRODUTO) SALDO ON PGE.IDSUBPRODUTO = SALDO.IDSUBPRODUTO
WHERE
	IDCONFIGECOMMERCE = 2 AND DESCRICAO IS NOT NULL AND
	PG.IDSUBPRODUTO = PGE.IDSUBPRODUTO AND
	PG.IDPRODUTO = PGE.IDPRODUTO AND
	PPP.IDEMPRESA = 1 AND
	P.IDPRODUTO = PG.IDPRODUTO AND
	P.IDPRODUTO = PGE.IDPRODUTO AND
	--P.FABRICANTE = :RA_MARCA AND
	(PG.FLAGINATIVO = :RA_STATUS OR :RA_STATUS = '%')
ORDER BY
	FABRICANTE