

SELECT 
	PRODS.FABRICANTE,
	ROUND(SUM(PRODS.ESTOQUE*LASTCUSTO.CUSTOULTIMACOMPRA),2) VALOR_ESTOQUE
FROM

	(SELECT 
		ESTOQUE_SINTETICO.IDSUBPRODUTO,
		PRODUTO.FABRICANTE,
		COALESCE(ESTOQUE_SINTETICO.QTDATUALESTOQUE,0) AS ESTOQUE
	FROM
		ESTOQUE_SINTETICO,
		PRODUTO
	WHERE
		ESTOQUE_SINTETICO.IDEMPRESA = :RA_IDEMPRESA AND
		ESTOQUE_SINTETICO.IDLOCALESTOQUE = :RA_IDLOCALESTOQUE AND
		ESTOQUE_SINTETICO.QTDATUALESTOQUE > 0 AND
	    ESTOQUE_SINTETICO.IDPRODUTO = PRODUTO.IDPRODUTO AND
	    PRODUTO.FABRICANTE LIKE '%BOSCH%' AND
	    ESTOQUE_SINTETICO.DTMOVIMENTO =  
	    	(SELECT   MAX(EST.DTMOVIMENTO)
	    	FROM     
				ESTOQUE_SINTETICO AS EST
			WHERE    
				ESTOQUE_SINTETICO.IDEMPRESA = EST.IDEMPRESA AND
			    ESTOQUE_SINTETICO.IDPRODUTO = EST.IDPRODUTO AND
			    ESTOQUE_SINTETICO.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
			    ESTOQUE_SINTETICO.IDLOCALESTOQUE = EST.IDLOCALESTOQUE AND
			    EST.DTMOVIMENTO <= DATE(:RA_DTFIM))) AS PRODS LEFT JOIN
	(SELECT     
		PRODUTO_GRADE_CUSTO_VIEW.IDSUBPRODUTO,
		PRODUTO_GRADE_CUSTO_VIEW.CUSTOULTIMACOMPRA
	FROM    
		PRODUTO_GRADE_CUSTO_VIEW
	WHERE     
		PRODUTO_GRADE_CUSTO_VIEW.IDEMPRESA = :RA_IDEMPRESA) AS LASTCUSTO ON PRODS.IDSUBPRODUTO = LASTCUSTO.IDSUBPRODUTO
GROUP BY
	PRODS.FABRICANTE
