SELECT
	DADOS.FABRICANTE,
	ESTOQUE_INICIAL,
	ESTOQUE_FINAL,
	(ESTOQUE_FINAL - ESTOQUE_INICIAL) VARIACAO,
	(ESTOQUE_FINAL * 100 /(SELECT ROUND(SUM((ESTOQUE * CUSTOGERENCIAL)),2) VALOR_ESTOQUE
							FROM
								(SELECT 
											ESTOQUE_SINTETICO.IDSUBPRODUTO,
											PRODUTO.FABRICANTE,
											COALESCE(ESTOQUE_SINTETICO.QTDATUALESTOQUE,0) AS ESTOQUE
										FROM
											ESTOQUE_SINTETICO,
											PRODUTO
										WHERE
											ESTOQUE_SINTETICO.IDEMPRESA = :RA_IDEMPRESA AND
											ESTOQUE_SINTETICO.IDLOCALESTOQUE = :RA_IDLOCALESTOQUE AND
											ESTOQUE_SINTETICO.QTDATUALESTOQUE > 0 AND
											IDSUBPRODUTO <> 2 AND
										    ESTOQUE_SINTETICO.IDPRODUTO = PRODUTO.IDPRODUTO AND
										    --PRODUTO.FABRICANTE LIKE UPPER (:RA_MARCA) AND
										    ESTOQUE_SINTETICO.DTMOVIMENTO =  
										    	(SELECT   MAX(EST.DTMOVIMENTO)
										    	FROM     
													ESTOQUE_SINTETICO AS EST
												WHERE    
													ESTOQUE_SINTETICO.IDEMPRESA = EST.IDEMPRESA AND
												    ESTOQUE_SINTETICO.IDPRODUTO = EST.IDPRODUTO AND
												    ESTOQUE_SINTETICO.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
												    ESTOQUE_SINTETICO.IDLOCALESTOQUE = EST.IDLOCALESTOQUE AND
												    EST.DTMOVIMENTO <= DATE(:RA_DTFIM))) AS PRODS3 LEFT JOIN
												    (SELECT     
											PRODUTO_GRADE_CUSTO_VIEW.IDSUBPRODUTO,
											PRODUTO_GRADE_CUSTO_VIEW.CUSTOGERENCIAL
										FROM    
											PRODUTO_GRADE_CUSTO_VIEW
										WHERE     
											PRODUTO_GRADE_CUSTO_VIEW.IDEMPRESA = :RA_IDEMPRESA) AS TOTALCUSTO 
											ON PRODS3.IDSUBPRODUTO = TOTALCUSTO.IDSUBPRODUTO)) || '%' PERNCET_ESTOQUE_TOTAL
	
FROM
	(SELECT 
		PRODS.FABRICANTE,
		ROUND(SUM(PRODS.ESTOQUE*ULTIMOCUSTO.CUSTOULTIMACOMPRA),2) ESTOQUE_INICIAL,
		ROUND(SUM(PRODS2.ESTOQUE*ULTIMOCUSTO.CUSTOULTIMACOMPRA),2) ESTOQUE_FINAL
	FROM
	
		(SELECT 
			ESTOQUE_SINTETICO.IDSUBPRODUTO,
			PRODUTO.FABRICANTE,
			COALESCE(ESTOQUE_SINTETICO.QTDATUALESTOQUE,0) AS ESTOQUE
		FROM
			ESTOQUE_SINTETICO,
			PRODUTO
		WHERE
			ESTOQUE_SINTETICO.IDEMPRESA = :RA_IDEMPRESA AND
			ESTOQUE_SINTETICO.IDLOCALESTOQUE = :RA_IDLOCALESTOQUE AND
			ESTOQUE_SINTETICO.QTDATUALESTOQUE > 0 AND
		    ESTOQUE_SINTETICO.IDPRODUTO = PRODUTO.IDPRODUTO AND
		    PRODUTO.FABRICANTE LIKE UPPER (:RA_MARCA) AND
		    ESTOQUE_SINTETICO.DTMOVIMENTO =  
		    	(SELECT   MAX(EST.DTMOVIMENTO)
		    	FROM     
					ESTOQUE_SINTETICO AS EST
				WHERE    
					ESTOQUE_SINTETICO.IDEMPRESA = EST.IDEMPRESA AND
				    ESTOQUE_SINTETICO.IDPRODUTO = EST.IDPRODUTO AND
				    ESTOQUE_SINTETICO.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
				    ESTOQUE_SINTETICO.IDLOCALESTOQUE = EST.IDLOCALESTOQUE AND
				    EST.DTMOVIMENTO <= DATE(:RA_DTINI))) AS PRODS LEFT JOIN
		(SELECT     
			PRODUTO_GRADE_CUSTO_VIEW.IDSUBPRODUTO,
			PRODUTO_GRADE_CUSTO_VIEW.CUSTOULTIMACOMPRA
		FROM    
			PRODUTO_GRADE_CUSTO_VIEW
		WHERE     
			PRODUTO_GRADE_CUSTO_VIEW.IDEMPRESA = :RA_IDEMPRESA) AS ULTIMOCUSTO ON PRODS.IDSUBPRODUTO = ULTIMOCUSTO.IDSUBPRODUTO
			
		LEFT JOIN
		(SELECT 
			ESTOQUE_SINTETICO.IDSUBPRODUTO,
			PRODUTO.FABRICANTE,
			COALESCE(ESTOQUE_SINTETICO.QTDATUALESTOQUE,0) AS ESTOQUE
		FROM
			ESTOQUE_SINTETICO,
			PRODUTO
		WHERE
			ESTOQUE_SINTETICO.IDEMPRESA = :RA_IDEMPRESA AND
			ESTOQUE_SINTETICO.IDLOCALESTOQUE = :RA_IDLOCALESTOQUE AND
			ESTOQUE_SINTETICO.QTDATUALESTOQUE > 0 AND
		    ESTOQUE_SINTETICO.IDPRODUTO = PRODUTO.IDPRODUTO AND
		    PRODUTO.FABRICANTE LIKE UPPER (:RA_MARCA)AND
		    ESTOQUE_SINTETICO.DTMOVIMENTO =  
		    	(SELECT   MAX(EST.DTMOVIMENTO)
		    	FROM     
					ESTOQUE_SINTETICO AS EST
				WHERE    
					ESTOQUE_SINTETICO.IDEMPRESA = EST.IDEMPRESA AND
				    ESTOQUE_SINTETICO.IDPRODUTO = EST.IDPRODUTO AND
				    ESTOQUE_SINTETICO.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
				    ESTOQUE_SINTETICO.IDLOCALESTOQUE = EST.IDLOCALESTOQUE AND
				    EST.DTMOVIMENTO <= DATE(:RA_DTFIM))) AS PRODS2 ON ULTIMOCUSTO.IDSUBPRODUTO = PRODS2.IDSUBPRODUTO
			
			
	GROUP BY
		PRODS.FABRICANTE) DADOS
ORDER BY
	ESTOQUE_FINAL DESC
		